// <auto-generated />
using System;
using System.Collections.Generic;
using Ambev.Store.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambev.Store.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambev.Store.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<decimal>>("Descontos")
                        .HasColumnType("numeric[]");

                    b.Property<Guid>("FilialRVenda")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NumeroVenda")
                        .HasColumnType("uuid");

                    b.Property<List<decimal>>("PrecosUnitarios")
                        .HasColumnType("numeric[]");

                    b.Property<List<Guid>>("Produtos")
                        .HasColumnType("uuid[]");

                    b.Property<List<int>>("Quantidades")
                        .HasColumnType("integer[]");

                    b.Property<List<decimal>>("ValorTotalItens")
                        .HasColumnType("numeric[]");

                    b.Property<decimal>("ValorTotalVenda")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
